import dotenv from "dotenv";
import pg from "pg";
import fs from "fs";
import path from "path";

dotenv.config();

const { Pool } = pg;

const pool = new Pool({
    host: process.env.DB_HOST || "localhost",
    port: Number(process.env.DB_PORT) || 5432,
    database: process.env.DB_NAME || "newdatainsights",
    user: process.env.DB_USER || "postgres",
    password: process.env.DB_PASSWORD || "",
});

const TABLES = [
    "companies",
    "users",
    "datasets",
    "permissions",
    "query_logs",
    "activity_logs",
    "password_reset_tokens"
];

const dumpData = async () => {
    try {
        let sql = "-- DATA SNAPSHOT GENERATED BY DUMP-DB.JS\n";
        sql += "BEGIN;\n\n";

        // Truncate tables in reverse order to clean up
        for (const table of [...TABLES].reverse()) {
            sql += `TRUNCATE TABLE ${table} CASCADE;\n`;
        }
        sql += "\n";

        for (const table of TABLES) {
            console.log(`Dumping table: ${table}...`);
            const { rows } = await pool.query(`SELECT * FROM ${table}`);
            
            if (rows.length === 0) continue;

            const columns = Object.keys(rows[0]);
            
            sql += `-- Table: ${table}\n`;
            for (const row of rows) {
                const values = columns.map(col => {
                    const val = row[col];
                    if (val === null) return "NULL";
                    if (typeof val === "boolean") return val;
                    if (typeof val === "number") return val;
                    if (val instanceof Date) return `'${val.toISOString()}'`;
                    if (typeof val === "object") return `'${JSON.stringify(val).replace(/'/g, "''")}'`;
                    return `'${val.replace(/'/g, "''")}'`;
                });

                sql += `INSERT INTO ${table} (${columns.join(", ")}) VALUES (${values.join(", ")});\n`;
            }
            sql += "\n";
        }

        sql += "COMMIT;";

        const outputPath = path.join(process.cwd(), "src", "config", "seed_data.sql");
        fs.writeFileSync(outputPath, sql);
        console.log(`\n✅ Snapshot successfully written to ${outputPath}`);
        console.log(`📊 Records dumped:`);
        process.exit(0);
    } catch (error) {
        console.error("❌ Export failed:", error.message);
        process.exit(1);
    } finally {
        await pool.end();
    }
};

dumpData();
