import { MOCK_USERS, MOCK_DATASETS, MOCK_ACTIVITY_LOGS, MOCK_PREVIEW_DATA } from './mock_data';

/**
 * Mock API Layer
 * Replicates all exports from api.js but returns static promises.
 */

const delay = (ms = 500) => new Promise(resolve => setTimeout(resolve, ms));

// ---- Auth ----
export const loginUser = async (email, password, role) => {
    await delay(800);
    return { success: true, token: "mock-jwt-token", role, name: "Demo User", email };
};

export const signupUser = async (data) => {
    await delay(1000);
    return { success: true, message: "Signup simulated in demo" };
};

export const getMe = async () => {
    return { success: true, user: { name: "Demo User", role: sessionStorage.getItem('role') || 'admin' } };
};

// ---- User Management (Admin) ----
export const getUsers = async (roleFilter) => {
    await delay(400);
    let filtered = MOCK_USERS;
    if (roleFilter && roleFilter !== 'all') {
        filtered = MOCK_USERS.filter(u => u.role === roleFilter);
    }
    return { success: true, users: filtered };
};

export const getUserStats = async () => {
    return { 
        success: true, 
        stats: { 
            total: MOCK_USERS.length, 
            active: MOCK_USERS.filter(u => u.is_active).length, 
            byRole: { admin: 1, employee: 3, viewer: 0 } 
        } 
    };
};

export const updateUserRole = async () => ({ success: true });
export const updateUserStatus = async () => ({ success: true });
export const deleteUser = async () => ({ success: true });
export const getPendingUsers = async () => ({ success: true, users: [], count: 0 });
export const approveUser = async () => ({ success: true });

// ---- Datasets ----
export const getDatasets = async () => {
    await delay(600);
    return { success: true, data: MOCK_DATASETS };
};

export const getDatasetsAdmin = async () => {
    await delay(600);
    return { success: true, data: MOCK_DATASETS };
};

export const uploadDataset = async (file) => {
    await delay(1500);
    return { success: true, message: "Upload simulated in demo mode", dataset_id: "ds_new" };
};

export const getDatasetStatus = async () => ({ success: true, status: "ready" });

export const getDashboardConfig = async () => {
    await delay(800);
    return { 
        success: true, 
        charts: [
            { id: 1, type: "bar", title: "Sales by Region", data: [{name: "North", value: 400}, {name: "South", value: 300}] },
            { id: 2, type: "line", title: "Monthly Growth", data: [{name: "Jan", value: 10}, {name: "Feb", value: 25}] }
        ],
        insights: ["Revenue up 12% YoY", "Churn reduced by 4%"],
        executive_summary: "Startup demo performance looks stable across all metrics."
    };
};

export const getAnalytics = async () => ({ success: true, insights: ["Mock insight 1", "Mock insight 2"] });

export const askQuery = async () => {
    await delay(2000);
    return { success: true, answer: "This is a simulated AI answer for the demo mode. In a live environment, this would be generated by your Python ML Engine." };
};

export const deleteDataset = async () => ({ success: true });

// ---- Dataset Assignment ----
export const assignDataset = async () => ({ success: true });
export const unassignDataset = async () => ({ success: true });
export const getDatasetAssignments = async () => ({ success: true, users: [MOCK_USERS[1]] });

export const getDatasetPreview = async () => {
    await delay(500);
    return { success: true, columns: MOCK_PREVIEW_DATA.columns, rows: MOCK_PREVIEW_DATA.rows };
};

export const downloadDataset = async (id, fileName) => {
    console.log("Mock Download Triggered for:", id);
    alert("Download behavior simulated for demo: " + (fileName || 'dataset.csv'));
    return true;
};

// ---- Password Reset ----
export const forgotPassword = async () => ({ success: true });
export const resetPassword = async () => ({ success: true });

// ---- Analytics & Logs ----
export const getCleanedData = async () => ({ success: true, rows: MOCK_PREVIEW_DATA.rows.slice(0, 10) });

export const getActivityLogs = async () => {
    await delay(400);
    return { success: true, logs: MOCK_ACTIVITY_LOGS };
};

export const getActivityStats = async () => ({ success: true, totalEvents: 120, avgSafety: "98%" });

export const getQueryVolume = async () => {
    return { 
        success: true, 
        normalized: [40, 60, 45, 70, 85, 90, 75], 
        days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] 
    };
};

const api = { defaults: { headers: { common: {} } } };
export default api;
